#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"

ITEM_DIR="$CONFIG_DIR/items"

bar=(
    height=32
    position=top
    shadow=off
    sticky=off
    padding_left=4
    padding_right=4
    color=$BAR_COLOR
    border_color=$BAR_BORDER_COLOR
    border_width=2
    corner_radius=10
    blur_radius=30
    margin=4
    y_offset=4
)

sketchybar --bar "${bar[@]}"

default=(
    padding_left=4
    padding_right=4
    icon.font="BerkeleyMono Nerd Font:Black:14"
    label.font="BerkeleyMono Nerd Font:SemiBold:14"
    icon.color=$ICON_COLOR
    label.color=$LABEL_COLOR
    icon.padding_left=4
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=4
    background.corner_radius=8
    background.height=24
)

sketchybar --default "${default[@]}"

source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/chevron.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --trigger aerospace_workspace_change

sketchybar --hotload true
sketchybar --update
