#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
    height=32
    position=top
    shadow=off
    sticky=off
    padding_left=4
    padding_right=4
    color=$BAR_COLOR
    border_color=$BAR_BORDER_COLOR
    border_width=2
    corner_radius=10
    blur_radius=30
    margin=4
    y_offset=4
)

sketchybar --bar "${bar[@]}"

default=(
    padding_left=4
    padding_right=4
    icon.font="BerkeleyMono Nerd Font:Black:16"
    label.font="BerkeleyMono Nerd Font:SemiBold:14"
    icon.color=$ICON_COLOR
    label.color=$LABEL_COLOR
    icon.padding_left=4
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=4
    background.corner_radius=8
    background.height=24
)

sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
             --set space.$sid \
             background.color=$BG1 \
             background.corner_radius=8 \
             background.height=24 \
             background.drawing=off \
             icon.font="BerkeleyMono Nerd Font:Medium:14.0" \
             label.font="sketchybar-app-font:Regular:16.0" \
             label="$sid" \
             label.padding_right=6 \
             icon.padding_left=6 \
             drawing=off \
             updates=when_shown \
             click_script="aerospace workspace $sid" \
             script="$PLUGIN_DIR/aerospace.sh" \
             --subscribe space.$sid aerospace_workspace_change front_app_switched
done

sketchybar --add item aerospace_refresh left \
           --set aerospace_refresh drawing=off \
                                  script="$PLUGIN_DIR/aerospace.sh" \
                                  updates=on \
           --subscribe aerospace_refresh aerospace_workspace_change front_app_switched

sketchybar --add item chevron left \
           --set chevron icon= \
                         icon.color=$ORANGE \
                         label.drawing=off \
                         background.drawing=off

sketchybar --add item front_app left \
           --set front_app script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched space_windows_change window_focus

sketchybar --add item clock right \
           --set clock update_freq=10 \
                      script="$PLUGIN_DIR/clock.sh" \
                      background.color=$BG1

sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
                       background.color=$BG1 \
           --subscribe volume volume_change

sketchybar --add item brew right \
           --set brew update_freq=43200 \
                     script="$PLUGIN_DIR/brew.sh" \
                     background.color=$BG1

sketchybar --add item cpu right \
           --set cpu update_freq=2 \
                    script="$PLUGIN_DIR/cpu.sh" \
                    background.color=$BG1

sketchybar --add item ram right \
           --set ram update_freq=2 \
                    script="$PLUGIN_DIR/ram.sh" \
                    background.color=$BG1

sketchybar --trigger aerospace_workspace_change

sketchybar --hotload true
sketchybar --update
