#!/usr/bin/env sh

# Global settings
yabai -m config layout bsp
yabai -m config top_padding                8
yabai -m config bottom_padding             8
yabai -m config left_padding               8
yabai -m config right_padding              8
yabai -m config window_gap                 8

# Borders (requires https://github.com/FelixKratz/JankyBorders)
borders active_color=0xff83a598 inactive_color=0xff92834f width=6.0 &

echo "yabai config loaded..."
